[package]
name = "virtual_exec_js"
version = "0.5.1"
edition = "2024"
repository = "https://github.com/i-am-unknown-81514525/virtual_exec"
authors = ["i-am-unknown-81514525" ]
readme = "README.md"
description = "WebAssembly binding library for virtual_exec"
license = "GPL-3.0"

[dependencies]
js-sys = "0.3.103"
serde = "1.0.229"
serde-wasm-bindgen = "0.6.5"
virtual_exec_core = { version = "0.5.0-alpha.2", path = "../virtual_exec_core", features = ["std", "parse", "binary_inst", "unsafe_check"] }
virtual_exec_type = { version = "0.5.0-alpha.2", path = "../virtual_exec_type" }
wasm-bindgen = "0.2.126"
wasm-bindgen-futures = "0.4.76"
async-lock = "3.4.2"
virtual_exec_std = { version = "0.5.0-alpha.2", path = "../virtual_exec_std", features = ["rand-js", "stream", "sys", "async", "tokio-io-util"], default-features = false }
console_error_panic_hook = { version = "0.1.7", optional = true }
cfg-if = "1.0.4"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
console_error_panic_hook = ["dep:console_error_panic_hook"]
default = ["console_error_panic_hook"]
